// packages/vue/src/browser/shell/shell.tsx
import { ApplicationShell } from '@malagu/core/lib/browser';
import { Component, Autowired } from '@malagu/core';
import { App } from 'vue';
import { APP } from '../annotation';

@Component({ id: ApplicationShell, rebind: true })
export class Shell implements ApplicationShell {

    @Autowired(APP)
    protected readonly app: App<Element>;

    attach(host: HTMLElement): void {
        this.app.mount(host);
    }
}

// dev-packages/cli/templates/sample-app/src/browser/shell.tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { ApplicationShell } from '@malagu/core/lib/browser';
import { Component } from '@malagu/core';
import { App } from './app';

@Component({ id: ApplicationShell, rebind: true })
export class Shell implements ApplicationShell {

    attach(host: HTMLElement): void {
        ReactDOM.render(<App/>, host);
    }
}
