// ui-packages/vue/src/browser/shell/shell.tsx
import { ApplicationShell } from '@celljs/core/lib/browser';
import { Component, Autowired } from '@celljs/core';
import { App } from 'vue';
import { APP } from '../annotation';

@Component({ id: ApplicationShell, rebind: true })
export class Shell implements ApplicationShell {

    @Autowired(APP)
    protected readonly app: App<Element>;

    attach(host: HTMLElement): void {
        this.app.mount(host);
    }
}

// ui-packages/react/src/browser/shell/shell.tsx
import { ApplicationShell } from '@celljs/core/lib/browser';
import { Component, Autowired } from '@celljs/core';
import { createRoot } from 'react-dom/client';
import * as React from 'react';
import { APP } from '../app';

@Component({ id: ApplicationShell, rebind: true })
export class Shell implements ApplicationShell {

    @Autowired(APP)
    protected readonly app: React.ComponentType;

    attach(host: HTMLElement): void {
        createRoot(host).render(React.createElement(this.app));
    }
}
